# Generated by Django 4.1.3 on 2022-11-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donation_request_view',
            fields=[
                ('ngo_name', models.CharField(default=None, max_length=50, primary_key=True, serialize=False)),
                ('domain', models.CharField(default=None, max_length=50)),
                ('head_of_ngo', models.CharField(default=None, max_length=50)),
                ('contactNo', models.CharField(default=None, max_length=10)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('donation_description', models.TextField(default=None)),
                ('donation_amount', models.CharField(default=None, max_length=10)),
            ],
            options={
                'db_table': 'post_request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='donation_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_description', models.TextField(blank=True, default=None)),
                ('donation_amount', models.CharField(blank=True, default=None, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngo_name', models.CharField(max_length=100)),
                ('domain', models.CharField(blank=True, max_length=20)),
                ('head_of_ngo', models.CharField(blank=True, max_length=30)),
                ('contactNo', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('registration_cerificate_Trust_Society', models.FileField(blank=True, upload_to='verification')),
                ('certificate_12A', models.FileField(blank=True, upload_to='verification')),
                ('beneficiary_profiles', models.FileField(blank=True, upload_to='verification')),
                ('verification_status', models.BooleanField(default=False)),
            ],
        ),
    ]
