# Generated by Django 4.1.3 on 2022-11-25 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='donation_request',
            new_name='donation_requst',
        ),
    ]
