# Generated by Django 4.1.3 on 2022-11-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reportnumber', models.CharField(blank=True, max_length=100, null=True)),
                ('raised_dt', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=100)),
                ('complaint_type', models.CharField(choices=[('Air Pollution', 'AirPollution'), ('Water Pollution', 'WaterPollution'), ('Noise Pollution', 'NoisePollution'), ('Solid Waste', 'SolidWaste'), ('Other', 'Other')], max_length=100)),
            ],
        ),
    ]
