# Generated by Django 4.1.3 on 2022-11-25 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_remove_post_img_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 11, 25, 5, 19, 25, 924115, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
